PROGRESS_BAR_LENGTH = 70

DEFAULT_ALLOWED_MIMETYPE_FILE = "allowed-mimetype.txt"
DEFAULT_INPUT_DIRECTORY = "input/"
DEFAULT_OUTPUT_DIRECTORY = "output/"

HEADER_COLLECTION_DIRECTORY = "headers/"

URL_SPLITTER = "\n"
MIME_TYPE_SPLITTER = ","
INPUT_FILE_PREFIX_SPLITTER = "-"

DEFAULT_INPUT_PREFIX = "default"
